name: Create world image
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-venture-api-container:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          cd dockerfiles/venture/api-container
          docker build -f Dockerfile . -t venture:api-container
      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Publish image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/venture
          docker tag venture:api-container $IMAGE_ID:api-container
          docker push $IMAGE_ID:api-container
