name: Create world image
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . -t world:latest
      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }} | docker logi ghcr.io -u $ --password-stdin"
      - name: Publish image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/latest
          docker tag world:latest
          docker push world:latest
