name: Create world image
on:
  push:
    tag: "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-world:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          cd ${{ github.ref_name }}/stable
          docker build -f Dockerfile . -t world:${{ github.ref_name }}
      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Publish image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/world
          docker tag venture:api-container $IMAGE_ID:${{ github.ref_name }}
          docker push $IMAGE_ID:${{ github.ref_name }}
