name: Create world image
on:
  push:
    branches:
        - main
    tags:
        - '*.*.*'

jobs:
  build-world:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          cd ${{ github.ref }}/stable
          docker build -f Dockerfile . -t world:${{ github.ref }}
      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Publish image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/world
          docker tag venture:api-container $IMAGE_ID:${{ github.ref }}
          docker push $IMAGE_ID:${{ github.ref }}
